export const OFFLINE_PATTERNS = [
  // Kardiyak
  "acs","afib",
  // Nörolojik
  "stroke","migraine","tension_headache",
  // Solunum / enfeksiyon
  "influenza","pneumonia",
  // GIS
  "gerd","ibs","peptic_ulcer",
  // Üriner
  "uti","pyelonephritis","kidney_stones",
  // Endokrin / metabolik
  "hypothyroidism","anemia","depression",
  // Kas-iskelet
  "lumbar_radiculopathy","cauda_equina",
  // Psikiyatrik
  "anxiety",
  "cellulitis","urticaria_allergy","contact_dermatitis","shingles","conjunctivitis","corneal_abrasion","retinal_detachment","acute_glaucoma"];

// Kapı → ilgili patternlar — tümü OFFLINE_PATTERNS'da mevcut
export const GATE_PATTERNS = {
  chest:    ["acs","afib","gerd","anxiety"],
  headache: ["stroke","migraine","tension_headache"],
  cold:     ["influenza","pneumonia"],
  stomach:  ["gerd","ibs","peptic_ulcer"],
  urinary:  ["uti","pyelonephritis","kidney_stones"],
  fatigue:  ["hypothyroidism","anemia","depression"],
  backpain: ["lumbar_radiculopathy","cauda_equina"],
  anxiety:  ["anxiety","afib","acs"],
  skin:     ["cellulitis","urticaria_allergy","contact_dermatitis","shingles"],
  eye:      ["acute_glaucoma","retinal_detachment","conjunctivitis","corneal_abrasion"],
};


export const MIN_QUESTIONS_BEFORE_DECISION = 5;

// Dinamik soru sıralaması — her cevaptan sonra kalan pattern dağılımına göre
// en ayırt edici soruyu seçer (information gain bazlı)

export const OFFLINE_PATTERN_NAMES_TR = {
  acs: "Akut Koroner Sendrom", stroke: "İnme / TİA", migraine: "Migren",
  uti: "İdrar Yolu Enfeksiyonu", hypothyroidism: "Hipotiroidizm",
  influenza: "Grip", gerd: "Mide Reflüsü", ibs: "İrritabl Bağırsak",
  lumbar_radiculopathy: "Bel Fıtığı / Sinir Sıkışması",
  cauda_equina: "Cauda Equina Sendromu", anxiety: "Anksiyete / Panik",
  anemia: "Anemi", pyelonephritis: "Böbrek İltihabı",
  head_injury:"Kafa Travması / Beyin Sarsıntısı", fracture_suspect:"Kırık Şüphesi", sprain_strain:"Burkulma / Zorlanma", laceration:"Kesik / Açık Yara",
  cellulitis:"Selülit (Cilt Enfeksiyonu)", urticaria_allergy:"Ürtiker / Alerjik Reaksiyon", contact_dermatitis:"Kontakt Dermatit / Egzama", shingles:"Zona",
  conjunctivitis:"Konjonktivit", corneal_abrasion:"Kornea Çizilmesi / Yabancı Cisim", retinal_detachment:"Retina Dekolmanı / Ani Görme Kaybı", acute_glaucoma:"Akut Glokom",
};
export const OFFLINE_URGENCY_TR = {
  RED: "Hemen 112'yi arayın veya acil servise gidin.",
  YELLOW: "Bugün bir doktora görünün.",
  GREEN: "Belirtiler kötüleşirse, yeni belirti eklenirse veya 48 saat içinde geçmezse bir doktora görünün.",
  GREY: "Örüntü güvenli otomatik karar için yeterince net değil. Lütfen görevli doktora başvurun ya da bugün doktorunuzu arayın.",
};
export const OFFLINE_URGENCY_EN = {
  RED: "Call 911 or go to the ED immediately.",
  YELLOW: "See a doctor today.",
  GREEN: "If symptoms worsen, new symptoms appear, or they don't improve within 48 hours, see a doctor.",
  GREY: "The pattern is not clear enough for a safe automated decision. Please see the on-site doctor or call your doctor today.",
};


export const PATTERNS = {
  hyperthyroidism:{name:"Hyperthyroidism / Graves",icd:"E05.0",base_prevalence:1.3,sprt_lr:2.8,risk:"moderate",triggers:["tremor","weight_loss","palpitations","heat_intolerance","sweating","anxiety","hair_loss","eye_changes","eye_bulging","frequent_bowel","insomnia","restlessness","increased_appetite"],required_any:["tremor","weight_loss","palpitations","heat_intolerance"],confirmatory:["tremor","weight_loss","palpitations"],routing_if_confirmed:"YELLOW",doctor_alert:"TSH + free T4 indicated. Three-symptom cluster (tremor + weight loss + palpitations) consistent with hyperthyroidism. Graves disease 60-80% of cases.",source:"AAFP 2025; ATA"},
  hypothyroidism:{name:"Hypothyroidism",icd:"E03.9",base_prevalence:4.6,sprt_lr:2.2,risk:"low",triggers:["fatigue","weight_gain","cold_intolerance","constipation","dry_skin","hair_loss","depression","slow_heart_rate","muscle_weakness","hoarse_voice","memory_problems","puffy_face","brittle_nails"],required_any:["fatigue","weight_gain","cold_intolerance","dry_skin"],confirmatory:["fatigue","weight_gain","cold_intolerance"],routing_if_confirmed:"YELLOW",doctor_alert:"TSH screening recommended. Hypothyroidism 5x more common in women. Pattern: fatigue + weight gain + cold intolerance.",source:"AAFP; ATA 2014"},
  diabetes_t2:{name:"Type 2 Diabetes",icd:"E11",base_prevalence:10.5,sprt_lr:3.1,risk:"moderate",triggers:["thirst","frequent_urination","fatigue","weight_loss","blurred_vision","tingling","slow_healing","hunger","frequent_infections","dark_skin_patches","numbness_feet","recurrent_thrush"],required_any:["thirst","frequent_urination","fatigue","weight_loss"],confirmatory:["thirst","frequent_urination","weight_loss"],routing_if_confirmed:"YELLOW",doctor_alert:"Classic triad (polyuria + polydipsia + fatigue/weight loss) highly suggestive of T2DM. Fasting glucose or HbA1c. ADA 2025.",source:"ADA Standards 2025"},
  diabetes_t1:{name:"Type 1 Diabetes",icd:"E10",base_prevalence:0.5,sprt_lr:3.8,risk:"high",triggers:["thirst","frequent_urination","weight_loss","fatigue","blurred_vision","abdominal_pain","nausea","fruity_breath","vomiting","rapid_onset"],required_any:["thirst","frequent_urination","weight_loss"],confirmatory:["thirst","frequent_urination","weight_loss"],routing_if_confirmed:"YELLOW",doctor_alert:"Rapid onset + younger age suggests T1DM vs T2DM. Urgent glucose + ketones. DKA risk.",source:"ADA 2025"},
  cushings:{name:"Cushing Syndrome",icd:"E24",base_prevalence:0.02,sprt_lr:3.2,risk:"moderate",triggers:["weight_gain","round_face","hump_back","stretch_marks","easy_bruising","high_blood_pressure","fatigue","depression","irregular_periods","muscle_weakness","acne","slow_healing"],required_any:["weight_gain","round_face","hump_back","stretch_marks"],confirmatory:["weight_gain","round_face","stretch_marks"],routing_if_confirmed:"YELLOW",doctor_alert:"Central obesity + facial rounding + purple striae: Cushing workup. 24h urine cortisol or overnight dexamethasone suppression.",source:"Endocrine Society 2022"},
  addisons:{name:"Adrenal Insufficiency (Addison's)",icd:"E27.1",base_prevalence:0.02,sprt_lr:3.5,risk:"high",triggers:["fatigue","weight_loss","low_blood_pressure","dizziness","nausea","vomiting","abdominal_pain","skin_darkening","salt_craving","muscle_weakness","depression"],required_any:["fatigue","skin_darkening","low_blood_pressure"],confirmatory:["fatigue","skin_darkening","weight_loss"],routing_if_confirmed:"YELLOW",doctor_alert:"Adrenal crisis risk. Morning cortisol + ACTH stimulation test. Salt craving + hyperpigmentation = classic Addison's.",source:"Endocrine Society 2016"},
  pcos:{name:"PCOS",icd:"E28.2",base_prevalence:8.0,sprt_lr:2.5,risk:"moderate",triggers:["irregular_periods","excess_hair","acne","weight_gain","thinning_hair","difficulty_conceiving","pelvic_pain","oily_skin","mood_changes"],required_any:["irregular_periods","excess_hair","acne"],confirmatory:["irregular_periods","excess_hair"],routing_if_confirmed:"YELLOW",doctor_alert:"Rotterdam criteria: 2 of 3 (irregular ovulation, hyperandrogenism, polycystic ovaries). Pelvic ultrasound + testosterone + LH/FSH.",source:"ESHRE/ASRM 2023"},
  acs:{name:"Acute Coronary Syndrome",icd:"I21",base_prevalence:19.0,sprt_lr:3.8,risk:"critical",triggers:["chest_pain","chest_tightness","chest_pressure","jaw_pain","left_arm_pain","shortness_of_breath","diaphoresis","nausea","back_pain","shoulder_pain","cold_sweat","dizziness"],required_any:["chest_pain","chest_tightness","chest_pressure","left_arm_pain"],confirmatory:["chest_pain","diaphoresis","shortness_of_breath"],routing_if_confirmed:"RED",doctor_alert:"ACS presentation. ECG + troponin immediately. TIMI score. Missed AMI 2.1% from ED.",source:"AHA/ACC 2021"},
  aortic_dissection:{name:"Aortic Dissection",icd:"I71.0",base_prevalence:0.4,sprt_lr:5.5,risk:"critical",triggers:["sudden_severe_chest_pain","tearing_pain","back_pain","pain_radiation_back","difference_in_arm_pulses","severe_chest_back_pain"],required_any:["sudden_severe_chest_pain","tearing_pain","back_pain"],confirmatory:["tearing_pain","back_pain"],routing_if_confirmed:"RED",doctor_alert:"Aortic dissection: sudden tearing pain sensitivity 84%. Emergency CT angiography. Mortality 1-2%/hour.",source:"ESC 2014; JACC"},
  heart_failure:{name:"Heart Failure",icd:"I50",base_prevalence:2.0,sprt_lr:3.5,risk:"high",triggers:["shortness_of_breath","leg_swelling","fatigue","orthopnea","waking_breathless","rapid_weight_gain","reduced_exercise","ankle_swelling","cough_lying_down"],required_any:["shortness_of_breath","leg_swelling"],confirmatory:["shortness_of_breath","leg_swelling","orthopnea"],routing_if_confirmed:"YELLOW",doctor_alert:"Framingham criteria: orthopnea + PND + leg edema. BNP + ECG + echo. Acute decompensation = emergency.",source:"ESC 2021; AHA 2024"},
  pe:{name:"Pulmonary Embolism",icd:"I26",base_prevalence:2.5,sprt_lr:4.2,risk:"critical",triggers:["shortness_of_breath","chest_pain","tachycardia","coughing_blood","recent_immobility","recent_surgery","leg_swelling_one_sided","low_oxygen","sudden_breathlessness"],required_any:["shortness_of_breath","chest_pain","coughing_blood"],confirmatory:["shortness_of_breath","tachycardia","low_oxygen"],routing_if_confirmed:"RED",doctor_alert:"Wells score. D-dimer if low prob; CT-PA if high. Emergency anticoagulation.",source:"ESC 2019"},
  stroke:{name:"Stroke / TIA",icd:"I64",base_prevalence:0.8,sprt_lr:5.8,risk:"critical",triggers:["facial_drooping","arm_weakness","speech_difficulty","sudden_headache","vision_change","confusion","numbness_one_side","dizziness_sudden","loss_of_balance","sudden_vision_loss"],required_any:["facial_drooping","arm_weakness","speech_difficulty","sudden_headache"],confirmatory:["facial_drooping","arm_weakness","speech_difficulty"],routing_if_confirmed:"RED",doctor_alert:"FAST positive. Thrombolysis window 4.5h. Call emergency immediately. No aspirin before imaging.",source:"AHA/ASA 2019"},
  hypertensive_crisis:{name:"Hypertensive Crisis",icd:"I16",base_prevalence:1.0,sprt_lr:3.8,risk:"critical",triggers:["severe_headache","chest_pain","shortness_of_breath","vision_change","nosebleed","confusion","nausea","vomiting","pulsating_headache"],required_any:["severe_headache","chest_pain","vision_change"],confirmatory:["severe_headache","vision_change","chest_pain"],routing_if_confirmed:"RED",doctor_alert:"BP >180/120. End-organ damage assessment: ECG, troponin, creatinine, fundoscopy. IV antihypertensive if symptomatic.",source:"ESC 2018"},
  afib:{name:"Atrial Fibrillation",icd:"I48",base_prevalence:2.0,sprt_lr:2.8,risk:"high",triggers:["palpitations","irregular_heartbeat","racing_heart","shortness_of_breath","fatigue","dizziness","chest_discomfort","reduced_exercise"],required_any:["palpitations","irregular_heartbeat","racing_heart"],confirmatory:["palpitations","irregular_heartbeat","shortness_of_breath"],routing_if_confirmed:"YELLOW",doctor_alert:"ECG urgently. CHA2DS2-VASc for stroke risk. Anticoagulation decision. Rate vs rhythm control.",source:"ESC 2020"},
  dvt:{name:"Deep Vein Thrombosis",icd:"I80.2",base_prevalence:1.5,sprt_lr:3.2,risk:"high",triggers:["leg_swelling_one_sided","leg_pain","leg_warmth","leg_redness","recent_immobility","recent_surgery","calf_pain","tenderness"],required_any:["leg_swelling_one_sided","leg_pain","leg_warmth"],confirmatory:["leg_swelling_one_sided","leg_pain","leg_redness"],routing_if_confirmed:"YELLOW",doctor_alert:"Wells DVT score. Doppler ultrasound. D-dimer if low probability. PE risk: anticoagulate if confirmed.",source:"ACCP 2016"},
  parkinsons:{name:"Parkinson Disease",icd:"G20",base_prevalence:0.3,sprt_lr:3.4,risk:"moderate",triggers:["tremor","stiffness","slow_movement","balance_problems","small_handwriting","loss_of_smell","sleep_disorder","constipation","soft_voice","masked_face","shuffling_gait"],required_any:["tremor","stiffness","slow_movement"],confirmatory:["tremor","stiffness","slow_movement"],routing_if_confirmed:"YELLOW",doctor_alert:"MDS criteria: bradykinesia + resting tremor or rigidity. Pill-rolling 4-6Hz tremor specific. Neurology referral.",source:"MDS Criteria 2015"},
  essential_tremor:{name:"Essential Tremor",icd:"G25.0",base_prevalence:4.0,sprt_lr:1.2,risk:"low",triggers:["tremor","tremor_with_action","head_tremor","voice_tremor","worsens_with_movement","improves_at_rest"],required_any:["tremor","tremor_with_action"],confirmatory:["tremor_with_action"],routing_if_confirmed:"GREEN",doctor_alert:"Action tremor vs resting tremor differentiates from Parkinson. Family history + alcohol responsiveness typical. Neurology if disabling.",source:"MDS; AAFP 2022"},
  migraine:{name:"Migraine",icd:"G43",base_prevalence:12.0,sprt_lr:1.8,risk:"low",triggers:["severe_headache","one_sided_headache","nausea","light_sensitivity","sound_sensitivity","aura","visual_disturbance","throbbing_headache","vomiting","worsens_with_activity"],required_any:["severe_headache","one_sided_headache"],confirmatory:["one_sided_headache","nausea","light_sensitivity"],routing_if_confirmed:"YELLOW",doctor_alert:"IHS criteria: 5+ attacks of unilateral throbbing 4-72h + nausea or photophobia. Rule out SAH if sudden onset worst-ever headache.",source:"IHS 2018"},
  meningitis:{name:"Meningitis",icd:"G03",base_prevalence:0.1,sprt_lr:5.2,risk:"critical",triggers:["severe_headache","neck_stiffness","fever","photophobia","vomiting","rash_non_blanching","confusion","sudden_onset_headache","jolt_sign"],required_any:["severe_headache","neck_stiffness","fever"],confirmatory:["fever","neck_stiffness","severe_headache"],routing_if_confirmed:"RED",doctor_alert:"Classic triad: fever + neck stiffness + altered consciousness. Non-blanching rash = meningococcal. Emergency IV antibiotics before LP.",source:"IDSA 2004; NICE NG240 2023"},
  ms:{name:"Multiple Sclerosis",icd:"G35",base_prevalence:0.3,sprt_lr:2.9,risk:"high",triggers:["vision_loss_one_eye","double_vision","numbness","tingling","weakness","balance_problems","fatigue","bladder_problems","cognitive_problems","heat_worsens"],required_any:["vision_loss_one_eye","numbness","weakness","balance_problems"],confirmatory:["vision_loss_one_eye","numbness","balance_problems"],routing_if_confirmed:"YELLOW",doctor_alert:"McDonald criteria. MRI brain + spine. Optic neuritis = classic first presentation. Neurology urgently.",source:"McDonald 2017; ECTRIMS"},
  epilepsy:{name:"Epilepsy / Seizure",icd:"G40",base_prevalence:1.2,sprt_lr:4.1,risk:"high",triggers:["seizure","convulsion","loss_of_consciousness","blank_staring","jerking_movements","confusion_after_event","tongue_biting","urinary_incontinence","post_ictal"],required_any:["seizure","convulsion","loss_of_consciousness"],confirmatory:["seizure","convulsion","jerking_movements"],routing_if_confirmed:"RED",doctor_alert:"New seizure = emergency workup. EEG + MRI. Rule out structural, metabolic, toxic causes. Status epilepticus = immediate IV benzodiazepine.",source:"ILAE 2017"},
  tension_headache:{name:"Tension-Type Headache",icd:"G44.2",base_prevalence:38.0,sprt_lr:0.8,risk:"low",triggers:["bilateral_headache","pressure_headache","band_around_head","mild_moderate_pain","stress_related","no_nausea","neck_muscle_tension"],required_any:["bilateral_headache","pressure_headache","band_around_head"],confirmatory:["bilateral_headache","pressure_headache"],routing_if_confirmed:"GREEN",doctor_alert:"Differentiate from migraine: bilateral, pressing/tightening, mild-moderate, no nausea. NSAIDs first-line. Rule out secondary causes if new pattern.",source:"IHS 2018"},
  lupus:{name:"Systemic Lupus (SLE)",icd:"M32.9",base_prevalence:0.1,sprt_lr:3.6,risk:"high",triggers:["butterfly_rash","joint_pain","fatigue","fever","hair_loss","mouth_sores","sun_sensitivity","chest_pain_pleurisy","kidney_symptoms","photosensitivity","rash_after_sun"],required_any:["butterfly_rash","joint_pain","sun_sensitivity"],confirmatory:["butterfly_rash","joint_pain","fatigue"],routing_if_confirmed:"YELLOW",doctor_alert:"EULAR/ACR 2019: ANA >= 1:80 sensitivity 98%. Multi-organ. Rheumatology referral. SLE mainly women 15-45.",source:"EULAR/ACR 2019"},
  ra:{name:"Rheumatoid Arthritis",icd:"M06.9",base_prevalence:1.0,sprt_lr:2.9,risk:"moderate",triggers:["joint_pain","morning_stiffness","joint_swelling","symmetric_joints","fatigue","joint_warmth","grip_weakness","small_joint_involvement","wrist_pain"],required_any:["joint_pain","morning_stiffness"],confirmatory:["joint_pain","morning_stiffness","symmetric_joints"],routing_if_confirmed:"YELLOW",doctor_alert:"ACR/EULAR 2010 criteria. RF + anti-CCP. Early DMARD prevents joint destruction. Rheumatology referral.",source:"ACR/EULAR 2010"},
  gout:{name:"Gout",icd:"M10",base_prevalence:3.9,sprt_lr:2.2,risk:"moderate",triggers:["joint_pain","big_toe_pain","sudden_joint_pain","red_swollen_joint","joint_warm","pain_at_night","tophi","recurrent_attacks"],required_any:["big_toe_pain","sudden_joint_pain","red_swollen_joint"],confirmatory:["big_toe_pain","sudden_joint_pain"],routing_if_confirmed:"YELLOW",doctor_alert:"Serum uric acid + joint aspiration if diagnostic uncertainty. NSAIDs or colchicine first-line. Allopurinol for prophylaxis.",source:"ACR 2020"},
  fibromyalgia:{name:"Fibromyalgia",icd:"M79.3",base_prevalence:2.0,sprt_lr:1.8,risk:"moderate",triggers:["widespread_pain","fatigue","sleep_problems","cognitive_difficulties","tender_points","headache","ibs_symptoms","depression","anxiety","pain_all_over"],required_any:["widespread_pain","fatigue","tender_points"],confirmatory:["widespread_pain","fatigue","sleep_problems"],routing_if_confirmed:"YELLOW",doctor_alert:"ACR 2010 criteria: widespread pain index ≥7 + symptom severity ≥5. Rule out inflammatory arthritis, thyroid disease. Multidisciplinary management.",source:"ACR 2016"},
  osteoporosis:{name:"Osteoporosis",icd:"M81",base_prevalence:10.0,sprt_lr:1.4,risk:"moderate",triggers:["back_pain","height_loss","fracture_low_trauma","stooped_posture","fragility_fracture","hip_pain","spine_pain"],required_any:["back_pain","height_loss","fracture_low_trauma"],confirmatory:["height_loss","fracture_low_trauma"],routing_if_confirmed:"YELLOW",doctor_alert:"DEXA scan. FRAX score. Risk: postmenopausal female, age >65, low BMI, smoking, steroids, family history. Calcium + Vit D + bisphosphonates.",source:"NOF 2023; USPSTF"},
  appendicitis:{name:"Appendicitis",icd:"K37",base_prevalence:5.3,sprt_lr:2.1,risk:"high",triggers:["abdominal_pain","right_lower_pain","nausea","vomiting","fever","pain_worsens_moving","loss_of_appetite","rebound_tenderness","pain_moves_to_right"],required_any:["abdominal_pain","right_lower_pain"],confirmatory:["right_lower_pain","nausea","fever"],routing_if_confirmed:"YELLOW",doctor_alert:"Alvarado score. Peritoneal signs = surgical emergency. WBC >10k LR+ 2.1. CT abdomen. Misdiagnosed 33% in women of childbearing age.",source:"AAFP 2008"},
  ibd:{name:"IBD (Crohn / UC)",icd:"K50",base_prevalence:0.4,sprt_lr:2.5,risk:"moderate",triggers:["chronic_diarrhea","blood_in_stool","abdominal_pain","weight_loss","fatigue","joint_pain","skin_rash","mouth_sores","night_sweats","rectal_bleeding","urgency"],required_any:["chronic_diarrhea","blood_in_stool","abdominal_pain"],confirmatory:["chronic_diarrhea","blood_in_stool","weight_loss"],routing_if_confirmed:"YELLOW",doctor_alert:"Fecal calprotectin + colonoscopy referral. Urgent if severe bleeding, toxic megacolon, or systemic deterioration.",source:"ACG IBD 2019"},
  celiac:{name:"Celiac Disease",icd:"K90.0",base_prevalence:1.0,sprt_lr:2.3,risk:"moderate",triggers:["diarrhea","bloating","weight_loss","fatigue","anemia","bone_pain","skin_rash","mouth_sores","gluten_triggered","abdominal_cramps","pale_stool"],required_any:["diarrhea","bloating","fatigue"],confirmatory:["diarrhea","weight_loss","fatigue"],routing_if_confirmed:"YELLOW",doctor_alert:"tTG-IgA serology (sensitivity 98%) — test BEFORE starting gluten-free diet. Duodenal biopsy to confirm. HLA-DQ2/DQ8.",source:"ACG Celiac 2023"},
  peptic_ulcer:{name:"Peptic Ulcer Disease",icd:"K25",base_prevalence:4.0,sprt_lr:1.6,risk:"moderate",triggers:["burning_stomach_pain","hunger_pain","pain_relieved_by_eating","nausea","vomiting","bloating","black_stool","nsaid_use","epigastric_pain"],required_any:["burning_stomach_pain","hunger_pain","epigastric_pain"],confirmatory:["burning_stomach_pain","pain_relieved_by_eating"],routing_if_confirmed:"YELLOW",doctor_alert:"H.pylori test + treat. Black/tarry stools = upper GI bleed, urgent endoscopy. Stop NSAIDs. PPI empiric.",source:"ACG 2017"},
  gerd:{name:"GERD / Acid Reflux",icd:"K21",base_prevalence:20.0,sprt_lr:1.4,risk:"low",triggers:["heartburn","acid_reflux","chest_burning","regurgitation","difficulty_swallowing","worse_lying_down","worse_after_eating","sour_taste","chronic_cough"],required_any:["heartburn","acid_reflux","chest_burning"],confirmatory:["heartburn","regurgitation","worse_lying_down"],routing_if_confirmed:"GREEN",doctor_alert:"PPI trial 4-8 weeks. Alarm symptoms (dysphagia, weight loss, bleeding) → urgent endoscopy. Barrett's esophagus surveillance if chronic.",source:"ACG GERD 2022"},
  bowel_obstruction:{name:"Bowel Obstruction",icd:"K56",base_prevalence:2.5,sprt_lr:3.2,risk:"critical",triggers:["severe_abdominal_pain","abdominal_distension","vomiting","no_bowel_movement","no_flatus","colicky_pain","nausea","vomiting_fecal"],required_any:["severe_abdominal_pain","no_bowel_movement","abdominal_distension"],confirmatory:["severe_abdominal_pain","no_bowel_movement","abdominal_distension"],routing_if_confirmed:"RED",doctor_alert:"Obstruction triad: pain + distension + obstipation. Upright AXR + CT. NPO + NGT + surgery consult. Strangulation = emergency.",source:"AAFP; StatPearls"},
  cholecystitis:{name:"Cholecystitis / Gallstones",icd:"K81",base_prevalence:3.0,sprt_lr:2.8,risk:"high",triggers:["right_upper_pain","pain_after_fatty_meal","nausea","vomiting","fever","pain_radiates_shoulder","right_shoulder_pain","jaundice","clay_stool"],required_any:["right_upper_pain","pain_after_fatty_meal"],confirmatory:["right_upper_pain","nausea","fever"],routing_if_confirmed:"YELLOW",doctor_alert:"Murphy's sign. Abdominal ultrasound. Acute cholecystitis = surgical referral. ERCP if choledocholithiasis suspected.",source:"WSES 2020"},
  pancreatitis:{name:"Acute Pancreatitis",icd:"K85",base_prevalence:0.5,sprt_lr:3.5,risk:"high",triggers:["severe_abdominal_pain","pain_radiates_back","nausea","vomiting","fever","abdominal_tenderness","worse_lying_flat","better_leaning_forward","alcohol_history"],required_any:["severe_abdominal_pain","pain_radiates_back"],confirmatory:["severe_abdominal_pain","nausea","pain_radiates_back"],routing_if_confirmed:"YELLOW",doctor_alert:"Lipase >3x ULN. CT abdomen for severity. NPO + IV fluids + analgesia. Gallstone = ERCP. Alcohol = abstinence counseling.",source:"ACG 2013"},
  ibs:{name:"Irritable Bowel Syndrome",icd:"K58",base_prevalence:11.0,sprt_lr:1.2,risk:"low",triggers:["abdominal_pain","bloating","diarrhea","constipation","alternating_bowel","pain_relieved_by_defecation","urgency","mucus_in_stool"],required_any:["abdominal_pain","bloating"],confirmatory:["abdominal_pain","alternating_bowel","pain_relieved_by_defecation"],routing_if_confirmed:"GREEN",doctor_alert:"Rome IV criteria. Exclude organic pathology (IBD, celiac, colorectal cancer). Low-FODMAP diet trial. No alarm features required for diagnosis.",source:"ACG IBS 2021"},
  copd:{name:"COPD",icd:"J44",base_prevalence:6.5,sprt_lr:2.4,risk:"moderate",triggers:["chronic_cough","progressive_breathlessness","sputum_production","wheezing","smoking_history","reduced_exercise","barrel_chest","morning_cough"],required_any:["chronic_cough","progressive_breathlessness"],confirmatory:["chronic_cough","progressive_breathlessness","smoking_history"],routing_if_confirmed:"YELLOW",doctor_alert:"Spirometry: FEV1/FVC <0.70 post-bronchodilator. GOLD staging. Smoking cessation first priority.",source:"GOLD 2024"},
  asthma:{name:"Asthma",icd:"J45",base_prevalence:8.0,sprt_lr:2.1,risk:"moderate",triggers:["wheezing","breathlessness","chest_tightness","cough","worse_at_night","exercise_triggered","allergen_triggered","variable_symptoms","seasonal_worsening"],required_any:["wheezing","breathlessness","chest_tightness"],confirmatory:["wheezing","breathlessness","exercise_triggered"],routing_if_confirmed:"YELLOW",doctor_alert:"GINA 2024: spirometry + reversibility testing. SpO2 <92% = emergency. Peak flow monitoring.",source:"GINA 2024"},
  pneumonia:{name:"Pneumonia",icd:"J18",base_prevalence:1.5,sprt_lr:3.2,risk:"high",triggers:["fever","cough","sputum","shortness_of_breath","chest_pain","fatigue","sweating","rigors","confusion_elderly"],required_any:["fever","cough","shortness_of_breath"],confirmatory:["fever","cough","shortness_of_breath"],routing_if_confirmed:"YELLOW",doctor_alert:"CURB-65 score. CXR. Blood cultures + sputum. Elderly: confusion may be only sign. Atypical: Legionella, Mycoplasma.",source:"BTS 2009; IDSA/ATS 2019"},
  depression:{name:"Major Depression",icd:"F32",base_prevalence:8.3,sprt_lr:2.0,risk:"moderate",triggers:["persistent_sadness","loss_of_interest","fatigue","sleep_changes","appetite_changes","concentration_problems","hopelessness","worthlessness","crying","social_withdrawal","suicidal_thoughts"],required_any:["persistent_sadness","loss_of_interest"],confirmatory:["persistent_sadness","loss_of_interest","fatigue"],routing_if_confirmed:"YELLOW",doctor_alert:"PHQ-9 recommended. Suicidal ideation = emergency psychiatric assessment. ≥2 weeks consistent with MDD. SSRI + therapy first-line.",source:"DSM-5-TR; APA 2023"},
  anxiety:{name:"Anxiety / Panic Disorder",icd:"F41",base_prevalence:19.1,sprt_lr:0.6,risk:"low",triggers:["racing_heart","chest_tightness","shortness_of_breath","dizziness","trembling","sweating","fear","avoidance","excessive_worry","muscle_tension","panic_attacks"],required_any:["racing_heart","chest_tightness","excessive_worry"],confirmatory:["racing_heart","chest_tightness","shortness_of_breath"],routing_if_confirmed:"GREEN",doctor_alert:"Rule out cardiac cause first (ECG). GAD-7 + PHQ-4. CBT + SSRI first-line. Panic disorder requires ruling out organic cause.",source:"NIMH 2024"},
  bipolar:{name:"Bipolar Disorder",icd:"F31",base_prevalence:2.8,sprt_lr:2.2,risk:"moderate",triggers:["mood_swings","elevated_mood","decreased_sleep","grandiosity","rapid_speech","impulsivity","depression_episodes","risky_behavior","racing_thoughts","irritability"],required_any:["mood_swings","elevated_mood","decreased_sleep"],confirmatory:["elevated_mood","decreased_sleep","rapid_speech"],routing_if_confirmed:"YELLOW",doctor_alert:"MDQ screening. Rule out substance use, thyroid, medications. Mood stabilizer (lithium/valproate). Psychiatry referral.",source:"DSM-5-TR; CANMAT 2023"},
  ptsd:{name:"PTSD",icd:"F43.1",base_prevalence:3.5,sprt_lr:2.0,risk:"moderate",triggers:["flashbacks","nightmares","avoidance","hypervigilance","emotional_numbing","sleep_problems","irritability","memory_problems","trauma_history"],required_any:["flashbacks","nightmares","avoidance","trauma_history"],confirmatory:["flashbacks","nightmares","hypervigilance"],routing_if_confirmed:"YELLOW",doctor_alert:"PCL-5 screening. Trauma-focused CBT or EMDR first-line. SSRIs (sertraline, paroxetine) FDA-approved. Assess for suicidality.",source:"VA/DoD 2023; APA"},
  ckd:{name:"Chronic Kidney Disease",icd:"N18",base_prevalence:15.0,sprt_lr:1.8,risk:"moderate",triggers:["fatigue","leg_swelling","foamy_urine","reduced_urine","back_pain","itching","nausea","loss_of_appetite","pale_skin","muscle_cramps","high_blood_pressure"],required_any:["fatigue","leg_swelling","foamy_urine"],confirmatory:["fatigue","leg_swelling","foamy_urine"],routing_if_confirmed:"YELLOW",doctor_alert:"eGFR + urine albumin-creatinine ratio. Nephrology if eGFR <30. CDC: 90% of CKD patients unaware.",source:"KDIGO 2022"},
  kidney_stones:{name:"Nephrolithiasis (Kidney Stones)",icd:"N20",base_prevalence:3.0,sprt_lr:3.5,risk:"high",triggers:["severe_flank_pain","colicky_pain","blood_in_urine","nausea","vomiting","pain_radiates_groin","urinary_urgency","painful_urination","fever"],required_any:["severe_flank_pain","colicky_pain","blood_in_urine"],confirmatory:["severe_flank_pain","colicky_pain","blood_in_urine"],routing_if_confirmed:"YELLOW",doctor_alert:"CT KUB (non-contrast) gold standard. Analgesics + IV fluids. Stones >6mm usually need urological intervention. Fever + stone = urological emergency.",source:"EAU 2022"},
  uti:{name:"Urinary Tract Infection",icd:"N39.0",base_prevalence:5.0,sprt_lr:2.1,risk:"moderate",triggers:["painful_urination","frequent_urination","urgency","cloudy_urine","blood_in_urine","lower_abdominal_pain","burning_urination","strong_urine_smell"],required_any:["painful_urination","frequent_urination","burning_urination"],confirmatory:["painful_urination","frequent_urination","urgency"],routing_if_confirmed:"YELLOW",doctor_alert:"Urine dipstick + MSU. Nitrofurantoin or trimethoprim first-line uncomplicated UTI. Pyelonephritis (fever + flank pain) = ciprofloxacin.",source:"EAU 2023; PHE"},
  pyelonephritis:{name:"Pyelonephritis",icd:"N10",base_prevalence:0.5,sprt_lr:3.2,risk:"high",triggers:["fever","flank_pain","back_pain","painful_urination","frequent_urination","nausea","vomiting","rigors","confusion"],required_any:["fever","flank_pain"],confirmatory:["fever","flank_pain","painful_urination"],routing_if_confirmed:"YELLOW",doctor_alert:"MSU + blood cultures. IV antibiotics if severe. CT if no response in 48h (rule out abscess/obstruction). Hospitalise if septic.",source:"EAU 2023"},
  nafld:{name:"Fatty Liver (NAFLD/MASLD)",icd:"K76.0",base_prevalence:25.0,sprt_lr:1.5,risk:"moderate",triggers:["fatigue","right_upper_pain","abdominal_fullness","elevated_liver_enzymes","obesity","diabetes","metabolic_syndrome","no_alcohol"],required_any:["fatigue","right_upper_pain","obesity"],confirmatory:["fatigue","obesity","diabetes"],routing_if_confirmed:"YELLOW",doctor_alert:"FIB-4 index (ADA 2025 for all T2DM). Liver ultrasound. Lifestyle modification primary treatment. NASH progression to cirrhosis risk.",source:"ADA 2025; AASLD 2023"},
  anemia:{name:"Anemia",icd:"D64.9",base_prevalence:5.6,sprt_lr:1.9,risk:"moderate",triggers:["fatigue","pale_skin","breathlessness","dizziness","cold_hands","palpitations","brittle_nails","pica","pale_gums","headache","weakness"],required_any:["fatigue","pale_skin","breathlessness"],confirmatory:["fatigue","pale_skin","dizziness"],routing_if_confirmed:"YELLOW",doctor_alert:"CBC with differential. Iron deficiency most common. Rule out GI bleed. B12/folate if macrocytic. WHO: 24.8% global prevalence.",source:"WHO 2023"},
  sleep_apnea:{name:"Obstructive Sleep Apnea",icd:"G47.3",base_prevalence:9.0,sprt_lr:1.9,risk:"moderate",triggers:["loud_snoring","witnessed_apnea","daytime_sleepiness","morning_headache","frequent_waking","obesity","large_neck","hypertension","gasping_sleep","dry_mouth"],required_any:["loud_snoring","daytime_sleepiness"],confirmatory:["loud_snoring","witnessed_apnea","daytime_sleepiness"],routing_if_confirmed:"YELLOW",doctor_alert:"STOP-BANG score. Polysomnography referral. High risk: obesity + HTN + male. Untreated OSA increases CVD risk 2-3x.",source:"AASM 2023"},
  cancer_red_flags:{name:"Cancer Red Flags",icd:"Z12",base_prevalence:0.5,sprt_lr:3.2,risk:"high",triggers:["unexplained_weight_loss","persistent_fatigue","unexplained_bleeding","persistent_cough","lump","change_in_bowel","difficulty_swallowing","night_sweats","bone_pain","blood_in_urine","blood_in_stool"],required_any:["unexplained_weight_loss","unexplained_bleeding","lump","persistent_cough"],confirmatory:["unexplained_weight_loss","persistent_fatigue"],routing_if_confirmed:"YELLOW",doctor_alert:"NICE NG12 2015 criteria. 2-week urgent cancer referral pathway. Specify symptom pattern for targeted workup.",source:"NICE NG12 2015"},
  ectopic_pregnancy:{name:"Ectopic Pregnancy",icd:"O00",base_prevalence:1.2,sprt_lr:4.5,risk:"critical",triggers:["abdominal_pain","pelvic_pain","missed_period","vaginal_bleeding","shoulder_pain","dizziness","fainting","positive_pregnancy_test"],required_any:["pelvic_pain","missed_period","vaginal_bleeding"],confirmatory:["pelvic_pain","missed_period"],routing_if_confirmed:"RED",doctor_alert:"MUST exclude in ALL females of reproductive age with abdominal/pelvic pain. Urine beta-hCG immediately. Ruptured ectopic = hemorrhagic shock.",source:"ACOG 2023"},
  sepsis:{name:"Sepsis",icd:"A41.9",base_prevalence:0.3,sprt_lr:4.9,risk:"critical",triggers:["high_fever","confusion","rapid_breathing","rapid_heart_rate","suspected_infection","extreme_fatigue","mottled_skin","not_urinating","very_cold","low_blood_pressure"],required_any:["high_fever","confusion","rapid_breathing"],confirmatory:["high_fever","rapid_heart_rate","confusion"],routing_if_confirmed:"RED",doctor_alert:"qSOFA ≥2. Sepsis-3. Hour-1 bundle: blood cultures, lactate, IV fluids, antibiotics. Mortality +7% per hour of delay.",source:"Surviving Sepsis 2021"},
  covid:{name:"COVID-19",icd:"U07.1",base_prevalence:2.0,sprt_lr:2.5,risk:"moderate",triggers:["fever","cough","shortness_of_breath","loss_of_smell","loss_of_taste","fatigue","body_aches","sore_throat","headache","diarrhea"],required_any:["fever","cough","loss_of_smell","loss_of_taste"],confirmatory:["fever","cough","loss_of_smell"],routing_if_confirmed:"YELLOW",doctor_alert:"RAT or PCR. High-risk patients (age >65, immunocompromised, comorbidities): antivirals within 5 days. Isolation guidance.",source:"WHO 2023; CDC"},
  influenza:{name:"Influenza",icd:"J11",base_prevalence:5.0,sprt_lr:2.0,risk:"low",triggers:["fever","body_aches","headache","fatigue","dry_cough","sore_throat","runny_nose","sudden_onset","chills"],required_any:["fever","body_aches","sudden_onset","sore_throat","cough","runny_nose"],confirmatory:["fever","body_aches","dry_cough"],routing_if_confirmed:"GREEN",doctor_alert:"Rapid flu test. Oseltamivir within 48h for high-risk. Annual vaccination. Secondary bacterial pneumonia risk.",source:"CDC; IDSA 2018"},
  lumbar_radiculopathy:{name:"Lumbar Disc / Radiculopathy",icd:"M54.4",base_prevalence:5.0,sprt_lr:3.0,risk:"moderate",triggers:["lower_back_pain","leg_pain","sciatica","numbness_leg","tingling_leg","weakness_leg","pain_radiates_leg","worse_sitting","better_walking","straight_leg_raise"],required_any:["lower_back_pain","leg_pain","sciatica"],confirmatory:["lower_back_pain","leg_pain","numbness_leg"],routing_if_confirmed:"YELLOW",doctor_alert:"SLR test sensitivity 80%. MRI if neurological deficit or red flags. Conservative: physio + NSAIDs. Surgery if cauda equina.",source:"NICE NG59; SPINE"},
  cauda_equina:{name:"Cauda Equina Syndrome",icd:"G83.4",base_prevalence:0.01,sprt_lr:6.0,risk:"critical",triggers:["lower_back_pain","saddle_anesthesia","bladder_dysfunction","bowel_dysfunction","bilateral_leg_weakness","sexual_dysfunction","urinary_retention","leg_numbness"],required_any:["saddle_anesthesia","bladder_dysfunction","urinary_retention"],confirmatory:["saddle_anesthesia","bladder_dysfunction","lower_back_pain"],routing_if_confirmed:"RED",doctor_alert:"SURGICAL EMERGENCY. MRI immediately. Decompression within 24-48h critical for recovery. Do not delay.",source:"NICE; BASS"},
  psoriasis:{name:"Psoriasis",icd:"L40",base_prevalence:2.0,sprt_lr:1.8,risk:"low",triggers:["red_plaques","silver_scales","itchy_skin","skin_patches","scalp_involvement","nail_changes","joint_pain","elbow_knee_rash"],required_any:["red_plaques","silver_scales","skin_patches"],confirmatory:["red_plaques","silver_scales"],routing_if_confirmed:"GREEN",doctor_alert:"PASI score. Dermatology if moderate-severe. Psoriatic arthritis in 30%: joint pain + psoriasis = rheumatology referral. Biologics for severe.",source:"BAD; AAD 2020"},
  acute_glaucoma:{name:"Acute Angle-Closure Glaucoma",icd:"H40.2",base_prevalence:0.1,sprt_lr:4.5,risk:"critical",triggers:["eye_pain","sudden_vision_loss","halos_around_lights","red_eye","headache","nausea","vomiting","blurred_vision"],required_any:["eye_pain","sudden_vision_loss","halos_around_lights"],confirmatory:["eye_pain","sudden_vision_loss","halos_around_lights"],routing_if_confirmed:"RED",doctor_alert:"Ophthalmic emergency. IOP measurement. IV acetazolamide + topical pressure-lowering drops. Ophthalmology immediately.",source:"AAO 2020"},
  head_injury:{name:"Head Injury / Concussion (mTBI)",icd:"S06.0",base_prevalence:1.2,sprt_lr:3.0,risk:"high",triggers:["head_trauma","headache","dizziness","nausea","brief_confusion","memory_gap","loss_of_consciousness","repeated_vomiting","seizure_after_injury"],required_any:["head_trauma"],confirmatory:["head_trauma","brief_confusion","memory_gap"],routing_if_confirmed:"YELLOW",doctor_alert:"Canadian CT Head Rule governs imaging. LOC, repeated vomiting, post-injury seizure, GCS drop, anticoagulant use = ED. Observe 24h for deterioration.",source:"Canadian CT Head Rule"},
  fracture_suspect:{name:"Suspected Fracture",icd:"T14.2",base_prevalence:1.5,sprt_lr:3.2,risk:"high",triggers:["injury_mechanism","deformity","unable_bear_weight","severe_swelling","heard_snap","limited_motion","open_wound","limb_numb_pale","bruising"],required_any:["injury_mechanism","deformity","heard_snap","unable_bear_weight"],confirmatory:["deformity","heard_snap","unable_bear_weight"],routing_if_confirmed:"YELLOW",doctor_alert:"Ottawa rules guide X-ray decision. Open wound over fracture site or neurovascular compromise (numb/pale/cold limb) = surgical emergency.",source:"Ottawa Rules"},
  sprain_strain:{name:"Sprain / Strain",icd:"S93.4",base_prevalence:6.0,sprt_lr:2.0,risk:"low",triggers:["injury_mechanism","joint_swelling","pain_on_movement","bruising","twisted_joint"],required_any:["injury_mechanism","twisted_joint"],confirmatory:["twisted_joint","joint_swelling"],routing_if_confirmed:"GREEN",doctor_alert:"RICE protocol. Ottawa criteria negative with partial weight-bearing supports conservative care. Re-assess at 72h if not improving.",source:"Ottawa Rules"},
  laceration:{name:"Laceration / Open Wound",icd:"S61.9",base_prevalence:2.5,sprt_lr:2.8,risk:"moderate",triggers:["open_cut","bleeding","gaping_wound","deep_cut","bleeding_uncontrolled","numb_below_cut"],required_any:["open_cut","bleeding"],confirmatory:["gaping_wound","deep_cut"],routing_if_confirmed:"YELLOW",doctor_alert:"Closure window ~6-12h (face up to 24h). Uncontrolled bleeding, tendon/nerve signs (distal numbness, loss of motion) = ED. Check tetanus status.",source:"ACEP"},
  cellulitis:{name:"Cellulitis",icd:"L03.9",base_prevalence:1.8,sprt_lr:3.5,risk:"high",triggers:["spreading_redness","warm_skin","skin_pain","skin_swelling","fever","red_streaks","chills"],required_any:["spreading_redness","warm_skin"],confirmatory:["spreading_redness","warm_skin"],routing_if_confirmed:"YELLOW",doctor_alert:"Mark borders to track spread. Fever, red streaks (lymphangitis), rapid progression or immunocompromise = IV antibiotics / ED. Rule out DVT in lower limb.",source:"IDSA 2014"},
  urticaria_allergy:{name:"Urticaria / Allergic Reaction",icd:"L50.9",base_prevalence:4.0,sprt_lr:2.2,risk:"moderate",triggers:["itchy_welts","hives","rash_after_exposure","skin_swelling","lip_face_swelling","throat_tightness","breathing_difficulty_allergy"],required_any:["itchy_welts","hives","rash_after_exposure"],confirmatory:["itchy_welts","hives"],routing_if_confirmed:"GREEN",doctor_alert:"Antihistamines first-line. ANY airway involvement (lip/tongue/throat swelling, stridor, wheeze) = anaphylaxis pathway: epinephrine + ED.",source:"WAO 2020"},
  contact_dermatitis:{name:"Contact Dermatitis / Eczema Flare",icd:"L23.9",base_prevalence:5.0,sprt_lr:1.8,risk:"low",triggers:["itchy_rash","dry_scaly_patches","rash_after_exposure","localized_redness"],required_any:["itchy_rash","localized_redness"],confirmatory:["rash_after_exposure","dry_scaly_patches"],routing_if_confirmed:"GREEN",doctor_alert:"Identify and remove trigger. Topical steroids + emollients. Weeping, honey-colored crust or fever suggests secondary infection.",source:"AAD"},
  shingles:{name:"Herpes Zoster (Shingles)",icd:"B02.9",base_prevalence:0.8,sprt_lr:5.0,risk:"high",triggers:["one_sided_band_rash","burning_pain_before_rash","blisters_cluster","skin_pain","rash_near_eye","fever"],required_any:["one_sided_band_rash","blisters_cluster"],confirmatory:["one_sided_band_rash","burning_pain_before_rash"],routing_if_confirmed:"YELLOW",doctor_alert:"Antivirals most effective <72h from rash onset. Ophthalmic involvement (rash near eye / nose tip, Hutchinson sign) is sight-threatening: urgent ophthalmology.",source:"CDC"},
  conjunctivitis:{name:"Conjunctivitis",icd:"H10.9",base_prevalence:4.5,sprt_lr:2.0,risk:"low",triggers:["red_eye","eye_discharge","gritty_feeling","itchy_eyes","crusted_lashes","watery_eyes"],required_any:["red_eye"],confirmatory:["eye_discharge","crusted_lashes"],routing_if_confirmed:"GREEN",doctor_alert:"Mostly viral and self-limited. True pain (not grit), photophobia, vision change or contact-lens wear = urgent evaluation (keratitis risk).",source:"AAO"},
  corneal_abrasion:{name:"Corneal Abrasion / Foreign Body",icd:"S05.0",base_prevalence:1.5,sprt_lr:3.0,risk:"moderate",triggers:["foreign_body_sensation","eye_pain","tearing","light_sensitivity","red_eye","pain_on_blinking"],required_any:["foreign_body_sensation","pain_on_blinking"],confirmatory:["foreign_body_sensation","pain_on_blinking"],routing_if_confirmed:"YELLOW",doctor_alert:"Fluorescein exam. Never patch contact-lens-related abrasions (pseudomonas). Retained foreign body, rust ring or penetrating mechanism = ophthalmology.",source:"AAO"},
  retinal_detachment:{name:"Retinal Detachment / Acute Vision Loss",icd:"H33.2",base_prevalence:0.1,sprt_lr:6.0,risk:"critical",triggers:["sudden_floaters","flashes_of_light","curtain_vision","painless_vision_loss","sudden_vision_loss"],required_any:["curtain_vision","sudden_vision_loss","painless_vision_loss","sudden_floaters"],confirmatory:["curtain_vision","painless_vision_loss"],routing_if_confirmed:"RED",doctor_alert:"Time-critical: macula-on detachment is a surgical emergency. Curtain/shadow, photopsia with floater shower, painless monocular loss = same-day retina service. Sudden total loss: consider CRAO (stroke pathway).",source:"AAO 2022"},
};


export const ALL_TRIGGERS = new Set(Object.values(PATTERNS).flatMap(p => p.triggers || []));
export const DANGER_TRIGGERS = ["jaundice","clay_stool","fever","tachycardia","shortness_of_breath","vomiting","fruity_breath","rapid_onset","abdominal_pain","low_blood_pressure","dizziness","rebound_tenderness","chest_pain","coughing_blood","loss_of_consciousness","repeated_vomiting","open_wound","limb_numb_pale","bleeding_uncontrolled","red_streaks","rash_near_eye","throat_tightness","lip_face_swelling","curtain_vision","sudden_vision_loss"];
