export const AKINATOR_GATES = {
  tr: [
    { id:"chest",    label:"Göğüs ağrısı",          sub:"Sıkışma, baskı, yanma hissi"          },
    { id:"headache", label:"Baş ağrısı",             sub:"Zonklama, basınç, sürekli ağrı"       },
    { id:"cold",     label:"Burun, boğaz, öksürük",  sub:"Akıntı, hapşırma, ses kısıklığı"     },
    { id:"stomach",  label:"Mide ve karın",           sub:"Bulantı, şişkinlik, yanma, ishal"     },
    { id:"urinary",  label:"İdrar şikayeti",          sub:"Yanma, sık gitme, ağrı"               },
    { id:"fatigue",  label:"Yorgunluk ve halsizlik",  sub:"Bitkinlik, kilo değişimi, üşüme"     },
    { id:"backpain", label:"Sırt ve bel ağrısı",      sub:"Ağrı, uyuşma, tutulma, bacağa vurma" },
    { id:"anxiety",  label:"Kaygı ve çarpıntı",       sub:"Panik, nefes darlığı, stres"         },
    { id:"skin",     label:"Cilt ve döküntü",         sub:"Kızarıklık, kaşıntı, kabarcık"       },
    { id:"eye",      label:"Göz şikayeti",            sub:"Ağrı, kızarıklık, görme değişikliği" },
  ],
  en: [
    { id:"chest",    label:"Chest pain",              sub:"Tightness, pressure, burning"         },
    { id:"headache", label:"Headache",                sub:"Throbbing, pressure, constant ache"   },
    { id:"cold",     label:"Nose, throat, cough",     sub:"Runny nose, sneezing, hoarseness"     },
    { id:"stomach",  label:"Stomach and abdomen",     sub:"Nausea, bloating, heartburn, diarrhoea"},
    { id:"urinary",  label:"Urinary complaint",       sub:"Burning, frequent urge, pain"         },
    { id:"fatigue",  label:"Fatigue and weakness",    sub:"Exhaustion, weight change, cold sensitivity"},
    { id:"backpain", label:"Back and lower back",     sub:"Pain, numbness, stiffness, leg radiation"},
    { id:"anxiety",  label:"Anxiety and palpitations",sub:"Panic, breathlessness, stress"        },
    { id:"skin",     label:"Skin and rash",           sub:"Redness, itching, blisters"           },
    { id:"eye",      label:"Eye complaint",           sub:"Pain, redness, vision change"         },
  ],
};

// Tüm dal soruları — her dal 10-12 soru, derin ayrım
export const AKINATOR_QUESTIONS = [

  // ══ GÖĞÜS DALI ══
  // ACS vs GERD vs Anksiyete ayrımı
  { id:"chest_scale",    ask_if:"chest",   type:"scale", weight:3,
    text_tr:"Şu anki göğüs ağrısını 1'den 10'a değerlendirin.",
    text_en:"Rate the chest pain you feel right now from 1 to 10.",
    scale_trigger:"chest_pain", scale_high_triggers:["chest_pressure","chest_tightness"] },
  { id:"chest_arm",      ask_if:"chest",   type:"yn",    weight:5,
    text_tr:"Sol kolunuzda, omzunuzda ya da çenenizde ağrı veya uyuşma var mı?",
    text_en:"Do you have pain or numbness in your left arm, shoulder or jaw?",
    triggers_yes:["left_arm_pain","jaw_pain","shoulder_pain"] },
  { id:"chest_sweat",    ask_if:"chest",   type:"yn",    weight:4,
    text_tr:"Soğuk terleme oluyor mu?",
    text_en:"Are you breaking out in a cold sweat?",
    triggers_yes:["diaphoresis","cold_sweat"] },
  { id:"chest_breath",   ask_if:"chest",   type:"yn",    weight:3,
    text_tr:"Nefes almak zorlaşıyor mu?",
    text_en:"Is breathing becoming difficult?",
    triggers_yes:["shortness_of_breath"] },
  { id:"chest_nausea",   ask_if:"chest",   type:"yn",    weight:3,
    text_tr:"Bulantı veya kusma var mı?",
    text_en:"Do you feel nauseous or are you vomiting?",
    triggers_yes:["nausea","vomiting"] },
  { id:"chest_burn",     ask_if:"chest",   type:"yn",    weight:3,
    text_tr:"Yemekten sonra veya yatınca daha mı kötü oluyor?",
    text_en:"Does it get worse after eating or when lying down?",
    triggers_yes:["heartburn","acid_reflux","worse_lying_down","worse_after_eating"] },
  { id:"chest_exertion", ask_if:"chest",   type:"yn",    weight:4,
    text_tr:"Eforla — yürüyünce veya merdiven çıkınca — ağrı artıyor mu?",
    text_en:"Does the pain increase with exertion — walking or climbing stairs?",
    triggers_yes:["chest_pain","chest_tightness"] },
  { id:"chest_rest",     ask_if:"chest",   type:"yn",    weight:3, depends_on:"chest_exertion",
    text_tr:"Dinlenince ağrı geçiyor mu?",
    text_en:"Does resting ease the pain?",
    triggers_yes:["chest_pressure"] },
  { id:"chest_duration", ask_if:"chest",   type:"yn",    weight:3, depends_on:"chest_arm",
    text_tr:"Ağrı 20 dakikadan uzun sürüyor mu?",
    text_en:"Has the pain lasted more than 20 minutes?",
    triggers_yes:["chest_pain"] },
  { id:"chest_acid",     ask_if:"chest",   type:"yn",    weight:3, depends_on:"chest_burn",
    text_tr:"Ağız içine ekşi veya acı bir tat geliyor mu?",
    text_en:"Do you get a sour or bitter taste in your mouth?",
    triggers_yes:["acid_reflux","regurgitation","sour_taste"] },
  { id:"chest_palpitat", ask_if:"chest",   type:"yn",    weight:3,
    text_tr:"Kalp çarpıntısı, düzensiz kalp atışı veya panik hissi var mı?",
    text_en:"Do you also have palpitations, irregular heartbeat or a sense of panic?",
    triggers_yes:["palpitations","racing_heart","irregular_heartbeat","panic_attacks","fear","excessive_worry"] },
  { id:"chest_back",     ask_if:"chest",   type:"yn",    weight:4, depends_on:"chest_arm",
    text_tr:"Ağrı sırta veya omuzlara yayılıyor mu?",
    text_en:"Does the pain radiate to your back or shoulders?",
    triggers_yes:["back_pain","shoulder_pain","pain_radiation_back"] },

  // ══ BAŞ AĞRISI DALI ══
  // İnme vs Migren vs Gerilim tipi kesin ayrım
  { id:"head_sudden",    ask_if:"headache",type:"yn",    weight:5,
    text_tr:"Ağrı saniyeler içinde, aniden mi geldi?",
    text_en:"Did the pain come on within seconds — suddenly?",
    triggers_yes:["sudden_headache"] },
  { id:"head_face",      ask_if:"headache",type:"yn",    weight:5,
    text_tr:"Yüzünüzde uyuşma, sarkma veya güçsüzlük var mı?",
    text_en:"Is there numbness, drooping or weakness in your face?",
    triggers_yes:["facial_drooping","numbness_one_side","vision_change"] },
  { id:"head_arm",       ask_if:"headache",type:"yn",    weight:5,
    text_tr:"Bir kolunuzda veya bacağınızda ani güçsüzlük var mı?",
    text_en:"Is there sudden weakness in one arm or leg?",
    triggers_yes:["arm_weakness"] },
  { id:"head_speech",    ask_if:"headache",type:"yn",    weight:5,
    text_tr:"Konuşmanızda bozulma veya kelime bulmakta güçlük var mı?",
    text_en:"Is your speech slurred or are you struggling to find words?",
    triggers_yes:["speech_difficulty"] },
  { id:"head_scale",     ask_if:"headache",type:"scale", weight:3,
    text_tr:"Ağrının şiddetini 1'den 10'a değerlendirin.",
    text_en:"Rate the headache intensity from 1 to 10.",
    scale_trigger:"severe_headache", scale_high_triggers:["throbbing_headache"] },
  { id:"head_side",      ask_if:"headache",type:"yn",    weight:4,
    text_tr:"Ağrı kafanızın sadece bir tarafında mı?",
    text_en:"Is the pain on just one side of your head?",
    triggers_yes:["one_sided_headache"] },
  { id:"head_light",     ask_if:"headache",type:"yn",    weight:4,
    text_tr:"Işık veya ses sizi rahatsız ediyor mu?",
    text_en:"Does light or noise bother you?",
    triggers_yes:["light_sensitivity","sound_sensitivity"] },
  { id:"head_nausea",    ask_if:"headache",type:"yn",    weight:3,
    text_tr:"Bulantı veya kusma var mı?",
    text_en:"Is there nausea or vomiting?",
    triggers_yes:["nausea","vomiting"] },
  { id:"head_throbbing", ask_if:"headache",type:"yn",    weight:3, depends_on:"head_side",
    text_tr:"Ağrı nabız atar gibi zonkluyor mu?",
    text_en:"Does the pain throb or pulse?",
    triggers_yes:["throbbing_headache"] },
  { id:"head_aura",      ask_if:"headache",type:"yn",    weight:3, depends_on:"head_side",
    text_tr:"Ağrıdan önce gözlerinizde parlama, karartı veya çizgiler görüyor muydunuz?",
    text_en:"Before the pain, did you see flashing lights, blind spots or zigzag lines?",
    triggers_yes:["aura","visual_disturbance"] },
  { id:"head_pressure",  ask_if:"headache",type:"yn",    weight:3,
    text_tr:"Ağrı zonklamak yerine kafanızı saran bir baskı veya kuşak gibi mi hissettiriyor?",
    text_en:"Does it feel like pressure or a tight band squeezing your head rather than throbbing?",
    triggers_yes:["bilateral_headache","pressure_headache","band_around_head","neck_muscle_tension","stress_related"] },
  { id:"head_worse_act", ask_if:"headache",type:"yn",    weight:2, depends_on:"head_nausea",
    text_tr:"Hareket edince veya fiziksel aktiviteyle ağrı artıyor mu?",
    text_en:"Does physical activity or movement make the headache worse?",
    triggers_yes:["severe_headache","worsens_with_activity"] },

  // ══ BURUN / BOĞAZ / ÖKSÜRÜK DALI ══
  // Grip vs Soğuk algınlığı vs Pnömoni ayrımı
  { id:"cold_runny",     ask_if:"cold",    type:"yn",    weight:2,
    text_tr:"Burun akıntısı veya burun tıkanıklığı var mı?",
    text_en:"Do you have a runny or blocked nose?",
    triggers_yes:["runny_nose"] },
  { id:"cold_fever",     ask_if:"cold",    type:"yn",    weight:4,
    text_tr:"Ateşiniz var mı?",
    text_en:"Do you have a fever?",
    triggers_yes:["fever"] },
  { id:"cold_body",      ask_if:"cold",    type:"yn",    weight:4,
    text_tr:"Tüm vücudunuz ağrıyor mu?",
    text_en:"Is your whole body aching?",
    triggers_yes:["body_aches"] },
  { id:"cold_onset",     ask_if:"cold",    type:"yn",    weight:4,
    text_tr:"Şikayetler birkaç saat içinde aniden mi geldi?",
    text_en:"Did the symptoms come on suddenly within a few hours?",
    triggers_yes:["sudden_onset"] },
  { id:"cold_throat",    ask_if:"cold",    type:"yn",    weight:3,
    text_tr:"Boğaz ağrısı var mı?",
    text_en:"Do you have a sore throat?",
    triggers_yes:["sore_throat"] },
  { id:"cold_cough",     ask_if:"cold",    type:"yn",    weight:3,
    text_tr:"Öksürük var mı?",
    text_en:"Do you have a cough?",
    triggers_yes:["cough","dry_cough"] },
  { id:"cold_breath",    ask_if:"cold",    type:"yn",    weight:4,
    text_tr:"Nefes darlığı veya nefes alırken güçlük oluyor mu?",
    text_en:"Do you have shortness of breath or difficulty breathing?",
    triggers_yes:["shortness_of_breath","chest_tightness"] },
  { id:"cold_sputum",    ask_if:"cold",    type:"yn",    weight:3, depends_on:"cold_cough",
    text_tr:"Öksürükle balgam veya renkli sekresyon çıkıyor mu?",
    text_en:"Are you coughing up phlegm or discoloured mucus?",
    triggers_yes:["sputum_production","cough"] },
  { id:"cold_smell",     ask_if:"cold",    type:"yn",    weight:3,
    text_tr:"Koku veya tat duyunuz azaldı mı?",
    text_en:"Has your sense of smell or taste decreased?",
    triggers_yes:["loss_of_smell","loss_of_taste"] },
  { id:"cold_rigors",    ask_if:"cold",    type:"yn",    weight:3,
    text_tr:"Kontrol edemediğiniz titreme nöbetleri oluyor mu?",
    text_en:"Are you having uncontrollable shivering fits?",
    triggers_yes:["rigors","chills"] },
  { id:"cold_severity",  ask_if:"cold",    type:"scale", weight:2,
    text_tr:"Kendinizi ne kadar kötü hissediyorsunuz? 1 hafif, 10 yataktan kalkamıyorum.",
    text_en:"How unwell do you feel? 1 = mild, 10 = can't get out of bed.",
    scale_trigger:"fatigue", scale_high_triggers:["headache","body_aches","fever"] },

  // ══ MİDE / KARIN DALI ══
  // GERD vs İBS vs Ülser vs Gastroenterit ayrımı
  { id:"stom_scale",     ask_if:"stomach", type:"scale", weight:3,
    text_tr:"Karın ağrısını 1'den 10'a değerlendirin.",
    text_en:"Rate your abdominal pain from 1 to 10.",
    scale_trigger:"abdominal_pain", scale_high_triggers:["severe_abdominal_pain","cramping"] },
  { id:"stom_nausea",    ask_if:"stomach", type:"yn",    weight:3,
    text_tr:"Bulantı veya kusma var mı?",
    text_en:"Do you have nausea or vomiting?",
    triggers_yes:["nausea","vomiting"] },
  { id:"stom_diarrhea",  ask_if:"stomach", type:"yn",    weight:3,
    text_tr:"İshal var mı?",
    text_en:"Do you have diarrhoea?",
    triggers_yes:["diarrhea"] },
  { id:"stom_upper",     ask_if:"stomach", type:"yn",    weight:3,
    text_tr:"Ağrı üst karında mı — göğüs kemiğinin hemen altında mı?",
    text_en:"Is the pain in the upper abdomen — just below the breastbone?",
    triggers_yes:["epigastric_pain","burning_stomach_pain"] },
  { id:"stom_eating",    ask_if:"stomach", type:"yn",    weight:3, depends_on:"stom_upper",
    text_tr:"Yemek yince ağrı geçiyor mu?",
    text_en:"Does eating ease the pain?",
    triggers_yes:["pain_relieved_by_eating"] },
  { id:"stom_burn",      ask_if:"stomach", type:"yn",    weight:4,
    text_tr:"Göğüste yanma veya ağıza ekşi sıvı geliyor mu?",
    text_en:"Do you have a burning in your chest or acid coming up into your mouth?",
    triggers_yes:["heartburn","acid_reflux","regurgitation","chest_burning"] },
  { id:"stom_lie",       ask_if:"stomach", type:"yn",    weight:3, depends_on:"stom_burn",
    text_tr:"Yatınca veya öne eğilince şikayetler daha mı kötü oluyor?",
    text_en:"Do symptoms get worse when you lie down or bend forward?",
    triggers_yes:["worse_lying_down","worse_after_eating"] },
  { id:"stom_swallow",    ask_if:"stomach", type:"yn",    weight:2, depends_on:"stom_burn",
    text_tr:"Yutkunmakta güçlük veya yutkunurken ağrı var mı?",
    text_en:"Do you have difficulty swallowing or pain when swallowing?",
    triggers_yes:["difficulty_swallowing","sour_taste"] },
  { id:"stom_blood",     ask_if:"stomach", type:"yn",    weight:5,
    text_tr:"Dışkıda kan var mı ya da siyah, katran gibi görünüyor mu?",
    text_en:"Is there blood in your stool, or does it look black and tarry?",
    triggers_yes:["blood_in_stool","black_stool","rectal_bleeding"] },
  { id:"stom_fever",     ask_if:"stomach", type:"yn",    weight:3,
    text_tr:"Ateş var mı?",
    text_en:"Do you have a fever?",
    triggers_yes:["fever"] },
  { id:"stom_bloat",     ask_if:"stomach", type:"yn",    weight:2,
    text_tr:"Belirgin şişkinlik veya gaz şikayeti var mı?",
    text_en:"Do you have noticeable bloating or gas?",
    triggers_yes:["bloating","constipation","alternating_bowel"] },
  { id:"stom_bowel",     ask_if:"stomach", type:"yn",    weight:2, depends_on:"stom_diarrhea",
    text_tr:"Tuvalete gidince ağrı geçiyor mu?",
    text_en:"Does the pain ease after having a bowel movement?",
    triggers_yes:["pain_relieved_by_defecation","urgency"] },
  { id:"stom_hunger",    ask_if:"stomach", type:"yn",    weight:2, depends_on:"stom_upper",
    text_tr:"Ağrı aç kaldığınızda daha mı kötü oluyor?",
    text_en:"Is the pain worse when you are hungry?",
    triggers_yes:["hunger_pain","epigastric_pain"] },

  // ══ İDRAR DALI ══
  // İYE vs Piyelonefrit vs Böbrek taşı ayrımı
  { id:"uri_burn",       ask_if:"urinary", type:"yn",    weight:5,
    text_tr:"İdrar yaparken yanma veya ağrı var mı?",
    text_en:"Do you feel burning or pain when urinating?",
    triggers_yes:["painful_urination","burning_urination"] },
  { id:"uri_freq",       ask_if:"urinary", type:"yn",    weight:4,
    text_tr:"Çok sık tuvalete gidiyor musunuz, her seferinde az mı çıkıyor?",
    text_en:"Are you going very often with little urine each time?",
    triggers_yes:["frequent_urination","urgency"] },
  { id:"uri_appear",     ask_if:"urinary", type:"yn",    weight:4,
    text_tr:"İdrar bulanık, kötü kokulu veya kanlı mı?",
    text_en:"Is the urine cloudy, foul-smelling or bloody?",
    triggers_yes:["cloudy_urine","strong_urine_smell","blood_in_urine"] },
  { id:"uri_fever",      ask_if:"urinary", type:"yn",    weight:4,
    text_tr:"Ateş var mı?",
    text_en:"Do you have a fever?",
    triggers_yes:["fever"] },
  { id:"uri_flank",      ask_if:"urinary", type:"yn",    weight:4,
    text_tr:"Yan tarafınızda veya sırt alt kısmında ağrı var mı?",
    text_en:"Do you have pain in your side or lower back?",
    triggers_yes:["flank_pain","back_pain"] },
  { id:"uri_colicky",    ask_if:"urinary", type:"yn",    weight:4, depends_on:"uri_flank",
    text_tr:"Ağrı dalgalar halinde mi geliyor — şiddetleniyor sonra hafifliyour mu?",
    text_en:"Does the pain come in waves — intensifying then easing?",
    triggers_yes:["colicky_pain","severe_flank_pain"] },
  { id:"uri_groin",      ask_if:"urinary", type:"yn",    weight:3, depends_on:"uri_flank",
    text_tr:"Ağrı kasığa veya uyluğa yayılıyor mu?",
    text_en:"Does the pain radiate to your groin or thigh?",
    triggers_yes:["pain_radiates_groin"] },
  { id:"uri_lower",      ask_if:"urinary", type:"scale", weight:2,
    text_tr:"Alt karın ağrısını 1'den 10'a değerlendirin.",
    text_en:"Rate any lower abdominal pain from 1 to 10.",
    scale_trigger:"lower_abdominal_pain", scale_high_triggers:["urgency"] },
  { id:"uri_nausea",     ask_if:"urinary", type:"yn",    weight:2,
    text_tr:"Bulantı, kusma veya titreme oluyor mu?",
    text_en:"Is there nausea, vomiting or rigors?",
    triggers_yes:["nausea","vomiting","rigors"] },

  // ══ YORGUNLUK DALI ══
  // Hipotiroid vs Anemi vs Depresyon ayrımı
  { id:"fat_scale",      ask_if:"fatigue", type:"scale", weight:3,
    text_tr:"Yorgunluğu 1'den 10'a değerlendirin. 1 hafif, 10 hiç kalkamıyorum.",
    text_en:"Rate your fatigue from 1 to 10. 1 = mild, 10 = can't get up.",
    scale_trigger:"fatigue", scale_high_triggers:["weakness"] },
  { id:"fat_cold",       ask_if:"fatigue", type:"yn",    weight:4,
    text_tr:"Herkesten daha çok üşüyor musunuz?",
    text_en:"Do you feel colder than the people around you?",
    triggers_yes:["cold_intolerance"] },
  { id:"fat_weight_gain",ask_if:"fatigue", type:"yn",    weight:4,
    text_tr:"Son birkaç ayda diyet yapmadan kilo aldınız mı?",
    text_en:"Have you gained weight recently without trying?",
    triggers_yes:["weight_gain"] },
  { id:"fat_pale",       ask_if:"fatigue", type:"yn",    weight:4,
    text_tr:"Cildiniz soluk mu, az hareketle nefes darlığı oluyor mu?",
    text_en:"Is your skin pale, or do you get breathless with little effort?",
    triggers_yes:["pale_skin","breathlessness","dizziness"] },
  { id:"fat_heart",      ask_if:"fatigue", type:"yn",    weight:3, depends_on:"fat_pale",
    text_tr:"Çarpıntı veya hızlı kalp atışı oluyor mu?",
    text_en:"Do you have palpitations or a racing heart?",
    triggers_yes:["palpitations","racing_heart"] },
  { id:"fat_sad",        ask_if:"fatigue", type:"yn",    weight:4,
    text_tr:"Sürekli üzgün, umutsuz veya hiçbir şeyden zevk alamıyor musunuz?",
    text_en:"Do you feel persistently sad, hopeless or unable to enjoy anything?",
    triggers_yes:["persistent_sadness","loss_of_interest","hopelessness"] },
  { id:"fat_sleep",      ask_if:"fatigue", type:"yn",    weight:3, depends_on:"fat_sad",
    text_tr:"Uyku bozukluğu var mı — çok az veya çok fazla uyuma?",
    text_en:"Do you have sleep disturbances — sleeping too little or too much?",
    triggers_yes:["sleep_changes","insomnia"] },
  { id:"fat_appetite",   ask_if:"fatigue", type:"yn",    weight:3, depends_on:"fat_sad",
    text_tr:"İştah değişikliği var mı — yemek istemiyor musunuz veya çok mu yiyorsunuz?",
    text_en:"Has your appetite changed significantly — eating much less or much more?",
    triggers_yes:["appetite_changes","loss_of_appetite"] },
  { id:"fat_concentrate",ask_if:"fatigue", type:"yn",    weight:2, depends_on:"fat_sad",
    text_tr:"Konsantrasyon güçlüğü veya karar vermekte zorlanma oluyor mu?",
    text_en:"Do you have difficulty concentrating or making decisions?",
    triggers_yes:["concentration_problems","memory_problems","social_withdrawal"] },
  { id:"fat_skin",       ask_if:"fatigue", type:"yn",    weight:3, depends_on:"fat_cold",
    text_tr:"Cilt kuru mu, normalden fazla saç mı dökülüyor?",
    text_en:"Is your skin dry, or are you losing more hair than usual?",
    triggers_yes:["dry_skin","hair_loss"] },
  { id:"fat_constip",    ask_if:"fatigue", type:"yn",    weight:2, depends_on:"fat_cold",
    text_tr:"Belirgin kabızlık var mı?",
    text_en:"Do you have noticeable constipation?",
    triggers_yes:["constipation"] },
  { id:"fat_voice",      ask_if:"fatigue", type:"yn",    weight:2, depends_on:"fat_cold",
    text_tr:"Sesiniz kalınlaştı mı ya da yüzünüz şiş görünüyor mu?",
    text_en:"Has your voice become deeper, or does your face look puffy?",
    triggers_yes:["hoarse_voice","puffy_face"] },
  { id:"fat_nails",      ask_if:"fatigue", type:"yn",    weight:2, depends_on:"fat_cold",
    text_tr:"Tırnaklarınız kırılgan mı veya el-ayak soğukluğu oluyor mu?",
    text_en:"Are your nails brittle, or do you have cold hands and feet?",
    triggers_yes:["brittle_nails","cold_hands"] },

  // ══ SIRT / BEL DALI ══
  // Disk fıtığı vs Cauda equina — erken yakalama
  { id:"back_scale",     ask_if:"backpain",type:"scale", weight:3,
    text_tr:"Bel ağrısını 1'den 10'a değerlendirin.",
    text_en:"Rate your back pain from 1 to 10.",
    scale_trigger:"lower_back_pain", scale_high_triggers:["stiffness"] },
  { id:"back_leg",       ask_if:"backpain",type:"yn",    weight:5,
    text_tr:"Ağrı bir bacağınıza yayılıyor mu?",
    text_en:"Does the pain spread down into one leg?",
    triggers_yes:["leg_pain","sciatica","pain_radiates_leg"] },
  { id:"back_numb",      ask_if:"backpain",type:"yn",    weight:5, depends_on:"back_leg",
    text_tr:"Bacakta uyuşma veya karıncalanma var mı?",
    text_en:"Do you have numbness or tingling in your leg?",
    triggers_yes:["numbness_leg","tingling_leg","weakness_leg"] },
  { id:"back_bladder",   ask_if:"backpain",type:"yn",    weight:6,
    text_tr:"İdrar yapmakta güçlük ya da idrarı tutamama oluyor mu?",
    text_en:"Are you having trouble urinating or losing bladder control?",
    triggers_yes:["urinary_retention","bladder_dysfunction"] },
  { id:"back_saddle",    ask_if:"backpain",type:"yn",    weight:6, depends_on:"back_bladder",
    text_tr:"Kasık, iç bacaklar veya kalça bölgesinde uyuşma var mı?",
    text_en:"Do you have numbness in the groin, inner thighs or buttocks?",
    triggers_yes:["saddle_anesthesia"] },
  { id:"back_bowel",     ask_if:"backpain",type:"yn",    weight:5, depends_on:"back_bladder",
    text_tr:"Dışkılamayı kontrol etmekte güçlük var mı?",
    text_en:"Are you having difficulty controlling your bowels?",
    triggers_yes:["bowel_dysfunction","saddle_anesthesia"] },
  { id:"back_both_legs", ask_if:"backpain",type:"yn",    weight:4, depends_on:"back_leg",
    text_tr:"Her iki bacakta da güçsüzlük veya uyuşma var mı?",
    text_en:"Do you have weakness or numbness in both legs?",
    triggers_yes:["bilateral_leg_weakness","numbness_leg"] },
  { id:"back_sit",       ask_if:"backpain",type:"yn",    weight:3, depends_on:"back_leg",
    text_tr:"Oturunca ağrı daha mı kötü oluyor?",
    text_en:"Does sitting make the pain worse?",
    triggers_yes:["worse_sitting"] },
  { id:"back_worse_morn",ask_if:"backpain",type:"yn",    weight:2,
    text_tr:"Sabah kalktığınızda ağrı daha mı şiddetli oluyor?",
    text_en:"Is the pain worse when you first get up in the morning?",
    triggers_yes:["lower_back_pain","stiffness"] },
  { id:"back_duration",  ask_if:"backpain",type:"yn",    weight:2,
    text_tr:"Bu ağrı 6 haftadan uzun süredir devam ediyor mu?",
    text_en:"Has this pain been going on for more than 6 weeks?",
    triggers_yes:["lower_back_pain"] },

  // ══ KAYGI / ÇARPINTI DALI ══
  // Panik bozukluğu vs GAD vs AFib ayrımı
  { id:"anx_chest_pain", ask_if:"anxiety", type:"yn",    weight:5,
    text_tr:"Göğüste ağrı, baskı veya sıkışma hissediyor musunuz?",
    text_en:"Do you have any chest pain, pressure or tightness?",
    triggers_yes:["chest_pain","chest_pressure","chest_tightness"] },
  { id:"anx_palp",       ask_if:"anxiety", type:"yn",    weight:4,
    text_tr:"Kalp çarpıntısı veya hızlı kalp atışı hissediyor musunuz?",
    text_en:"Do you feel your heart pounding or racing?",
    triggers_yes:["racing_heart","palpitations"] },
  { id:"anx_irregular",  ask_if:"anxiety", type:"yn",    weight:4,
    text_tr:"Kalp atışınız düzensiz mi — zaman zaman atlıyor gibi mi?",
    text_en:"Does your heart feel irregular — like it skips beats sometimes?",
    triggers_yes:["irregular_heartbeat","palpitations"] },
  { id:"anx_breath",     ask_if:"anxiety", type:"yn",    weight:4,
    text_tr:"Nefes darlığı veya boğuluyormuş gibi his var mı?",
    text_en:"Do you feel short of breath or like you can't get enough air?",
    triggers_yes:["shortness_of_breath","chest_tightness"] },
  { id:"anx_panic",      ask_if:"anxiety", type:"yn",    weight:4,
    text_tr:"Aniden gelen yoğun korku veya panik atakları oluyor mu?",
    text_en:"Do you have sudden intense fear or panic attacks?",
    triggers_yes:["panic_attacks","fear"] },
  { id:"anx_worry",      ask_if:"anxiety", type:"yn",    weight:3,
    text_tr:"Durduramadığınız, günlük hayatı etkileyen aşırı endişe var mı?",
    text_en:"Do you have uncontrollable worry that affects daily life?",
    triggers_yes:["excessive_worry","muscle_tension"] },
  { id:"anx_scale",      ask_if:"anxiety", type:"scale", weight:3, depends_on:"anx_worry",
    text_tr:"Kaygı veya gerginliğini 1'den 10'a değerlendirin.",
    text_en:"Rate your anxiety or tension from 1 to 10.",
    scale_trigger:"excessive_worry", scale_high_triggers:["panic_attacks","muscle_tension"] },
  { id:"anx_dizziness",  ask_if:"anxiety", type:"yn",    weight:3, depends_on:"anx_palp",
    text_tr:"Baş dönmesi veya bayılacakmış gibi his oluyor mu?",
    text_en:"Do you feel dizzy or like you might faint?",
    triggers_yes:["dizziness"] },
  { id:"anx_physical",   ask_if:"anxiety", type:"yn",    weight:2, depends_on:"anx_panic",
    text_tr:"Titreme, terleme veya bulantı gibi fiziksel belirtiler var mı?",
    text_en:"Do you have physical symptoms like trembling, sweating or nausea?",
    triggers_yes:["trembling","sweating","nausea"] },
  { id:"anx_avoidance",  ask_if:"anxiety", type:"yn",    weight:3, depends_on:"anx_worry",
    text_tr:"Belirli yerlere veya durumlardan kaçınıyor musunuz — toplu taşıma, kalabalık gibi?",
    text_en:"Do you avoid certain places or situations — like public transport or crowds?",
    triggers_yes:["avoidance","excessive_worry","fear"] },
  { id:"anx_exertion",   ask_if:"anxiety", type:"yn",    weight:3, depends_on:"anx_chest_pain",
    text_tr:"Bu belirtiler efor sırasında — yürüyünce — daha mı kötü oluyor?",
    text_en:"Do these symptoms get worse with physical effort — like walking?",
    triggers_yes:["reduced_exercise","shortness_of_breath"] },

  // ══ SÜRE (tüm kapılar) ══
  { id:"dur_chest", ask_if:"chest", type:"yn", weight:4,
    text_tr:"Bu şikayet son birkaç saat içinde aniden mi başladı?",
    text_en:"Did this start suddenly, within the last few hours?",
    triggers_yes:["rapid_onset","sudden_onset"] },
  { id:"dur_headache", ask_if:"headache", type:"yn", weight:4,
    text_tr:"Bu şikayet son birkaç saat içinde aniden mi başladı?",
    text_en:"Did this start suddenly, within the last few hours?",
    triggers_yes:["rapid_onset","sudden_onset","sudden_headache"] },
  { id:"dur_cold", ask_if:"cold", type:"yn", weight:4,
    text_tr:"Bu şikayet son birkaç saat içinde aniden mi başladı?",
    text_en:"Did this start suddenly, within the last few hours?",
    triggers_yes:["rapid_onset","sudden_onset"] },
  { id:"dur_stomach", ask_if:"stomach", type:"yn", weight:4,
    text_tr:"Bu şikayet son birkaç saat içinde aniden mi başladı?",
    text_en:"Did this start suddenly, within the last few hours?",
    triggers_yes:["rapid_onset","sudden_onset"] },
  { id:"dur_urinary", ask_if:"urinary", type:"yn", weight:4,
    text_tr:"Bu şikayet son birkaç saat içinde aniden mi başladı?",
    text_en:"Did this start suddenly, within the last few hours?",
    triggers_yes:["rapid_onset","sudden_onset"] },
  { id:"dur_fatigue", ask_if:"fatigue", type:"yn", weight:4,
    text_tr:"Bu şikayet son birkaç saat içinde aniden mi başladı?",
    text_en:"Did this start suddenly, within the last few hours?",
    triggers_yes:["rapid_onset","sudden_onset"] },
  { id:"dur_backpain", ask_if:"backpain", type:"yn", weight:4,
    text_tr:"Bu şikayet son birkaç saat içinde aniden mi başladı?",
    text_en:"Did this start suddenly, within the last few hours?",
    triggers_yes:["rapid_onset","sudden_onset"] },
  { id:"dur_anxiety", ask_if:"anxiety", type:"yn", weight:4,
    text_tr:"Bu şikayet son birkaç saat içinde aniden mi başladı?",
    text_en:"Did this start suddenly, within the last few hours?",
    triggers_yes:["rapid_onset","sudden_onset"] },
  { id:"dur_skin", ask_if:"skin", type:"yn", weight:4,
    text_tr:"Bu şikayet son birkaç saat içinde aniden mi başladı?",
    text_en:"Did this start suddenly, within the last few hours?",
    triggers_yes:["rapid_onset","sudden_onset"] },
  { id:"dur_eye", ask_if:"eye", type:"yn", weight:4,
    text_tr:"Bu şikayet son birkaç saat içinde aniden mi başladı?",
    text_en:"Did this start suddenly, within the last few hours?",
    triggers_yes:["rapid_onset","sudden_onset"] },

  // ══ CİLT / DÖKÜNTÜ DALI ══
  { id:"skin_spread", ask_if:"skin", type:"yn", weight:5,
    text_tr:"Ciltte yayılan ve dokununca sıcak hissedilen bir kızarıklık var mı?",
    text_en:"Is there spreading redness that feels warm to the touch?",
    triggers_yes:["spreading_redness","warm_skin"] },
  { id:"skin_fever", ask_if:"skin", type:"yn", weight:5,
    text_tr:"Ateşiniz ya da titremeniz var mı?",
    text_en:"Do you have fever or chills?",
    triggers_yes:["fever","chills"] },
  { id:"skin_streak", ask_if:"skin", type:"yn", weight:6, depends_on:"skin_spread",
    text_tr:"Kızarıklıktan vücuda doğru çizgi halinde kırmızı hatlar ilerliyor mu?",
    text_en:"Are red streaks spreading from the area toward the body?",
    triggers_yes:["red_streaks"] },
  { id:"skin_hives", ask_if:"skin", type:"yn", weight:4,
    text_tr:"Kaşıntılı, kabarık döküntüler (kurdeşen) var mı?",
    text_en:"Do you have itchy, raised welts (hives)?",
    triggers_yes:["itchy_welts","hives"] },
  { id:"skin_expose", ask_if:"skin", type:"yn", weight:3,
    text_tr:"Yeni bir ürün, yiyecek, ilaç ya da böcek temasından sonra mı başladı?",
    text_en:"Did it start after a new product, food, medication, or insect contact?",
    triggers_yes:["rash_after_exposure"] },
  { id:"skin_swellface", ask_if:"skin", type:"yn", weight:6,
    text_tr:"Dudak veya dilde şişme ya da boğazda daralma hissi var mı?",
    text_en:"Any swelling of the lips or tongue, or tightness in the throat?",
    triggers_yes:["lip_face_swelling","throat_tightness"] },
  { id:"skin_band", ask_if:"skin", type:"yn", weight:5,
    text_tr:"Vücudun tek tarafında bant şeklinde ağrılı kabarcıklar var mı?",
    text_en:"Painful clustered blisters in a band on one side of the body?",
    triggers_yes:["one_sided_band_rash","blisters_cluster"] },
  { id:"skin_burnpain", ask_if:"skin", type:"yn", weight:4, depends_on:"skin_band",
    text_tr:"Döküntüden önce o bölgede yanma ya da karıncalanma var mıydı?",
    text_en:"Was there burning or tingling in that area before the rash appeared?",
    triggers_yes:["burning_pain_before_rash"] },
  { id:"skin_eye", ask_if:"skin", type:"yn", weight:6, depends_on:"skin_band",
    text_tr:"Döküntü göz çevresine ya da burun ucuna yakın mı?",
    text_en:"Is the rash near the eye or the tip of the nose?",
    triggers_yes:["rash_near_eye"] },
  { id:"skin_itchdry", ask_if:"skin", type:"yn", weight:2,
    text_tr:"Söz konusu bölgeler kuru, pullu ve kaşıntılı mı?",
    text_en:"Are the patches dry, scaly, and itchy?",
    triggers_yes:["itchy_rash","dry_scaly_patches","localized_redness"] },

  // ══ GÖZ DALI ══
  { id:"eye_pain", ask_if:"eye", type:"yn", weight:5,
    text_tr:"Gözde belirgin ağrı var mı (batma değil, gerçek ağrı)?",
    text_en:"Is there real pain in the eye (not just a gritty feeling)?",
    triggers_yes:["eye_pain"] },
  { id:"eye_vision", ask_if:"eye", type:"yn", weight:6,
    text_tr:"Görmede ani azalma ya da kayıp oldu mu?",
    text_en:"Has there been a sudden decrease or loss of vision?",
    triggers_yes:["sudden_vision_loss","painless_vision_loss"] },
  { id:"eye_curtain", ask_if:"eye", type:"yn", weight:6,
    text_tr:"Görme alanınıza perde ya da gölge iner gibi oldu mu?",
    text_en:"Did a curtain or shadow seem to come down over your vision?",
    triggers_yes:["curtain_vision"] },
  { id:"eye_flash", ask_if:"eye", type:"yn", weight:5,
    text_tr:"Ani ışık çakmaları ya da yoğun uçuşan noktalar görüyor musunuz?",
    text_en:"Are you seeing flashes of light or a sudden shower of floaters?",
    triggers_yes:["flashes_of_light","sudden_floaters"] },
  { id:"eye_halo", ask_if:"eye", type:"yn", weight:5,
    text_tr:"Işıkların etrafında renkli haleler görüyor musunuz?",
    text_en:"Do you see halos around lights?",
    triggers_yes:["halos_around_lights"] },
  { id:"eye_red", ask_if:"eye", type:"yn", weight:3,
    text_tr:"Gözünüz kızarık mı?",
    text_en:"Is the eye red?",
    triggers_yes:["red_eye"] },
  { id:"eye_disch", ask_if:"eye", type:"yn", weight:3,
    text_tr:"Çapaklanma ya da akıntı var mı?",
    text_en:"Is there discharge or crusting?",
    triggers_yes:["eye_discharge","crusted_lashes"] },
  { id:"eye_fb", ask_if:"eye", type:"yn", weight:4,
    text_tr:"Gözde yabancı cisim batması hissi ya da göz kırparken ağrı var mı?",
    text_en:"A foreign-body sensation, or pain when blinking?",
    triggers_yes:["foreign_body_sensation","pain_on_blinking"] },
  { id:"eye_photo", ask_if:"eye", type:"yn", weight:3,
    text_tr:"Işığa bakmak gözü rahatsız ediyor mu?",
    text_en:"Does light bother the eye?",
    triggers_yes:["light_sensitivity"] },
  { id:"eye_nausea", ask_if:"eye", type:"yn", weight:4, depends_on:"eye_pain",
    text_tr:"Göz ağrısıyla birlikte bulantı ya da kusma var mı?",
    text_en:"Nausea or vomiting along with the eye pain?",
    triggers_yes:["nausea","vomiting"] },
];


// Tüm offline patternlar — tüm gate pattern'larını kapsıyor
